/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rng_rpg;

/**
 *
 * @author 802709
 */
public class Problems extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Problems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ansButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        probBox = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ansBox = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        probButton = new javax.swing.JButton();
        heroHealthBox = new javax.swing.JTextField();
        enemyHealthBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ansButton.setText("Ok!");
        ansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(probBox);

        jScrollPane2.setViewportView(ansBox);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Problem:");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel2.setText("Type your answer here: ");

        probButton.setText("Get New Problem");
        probButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probButtonActionPerformed(evt);
            }
        });

        heroHealthBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        heroHealthBox.setForeground(new java.awt.Color(0, 0, 255));
        heroHealthBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heroHealthBoxActionPerformed(evt);
            }
        });

        enemyHealthBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enemyHealthBox.setForeground(new java.awt.Color(153, 0, 0));
        enemyHealthBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enemyHealthBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Your Health: ");

        jLabel4.setText("Enemy Health:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(149, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heroHealthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(probButton)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enemyHealthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ansButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(probButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heroHealthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enemyHealthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansButtonActionPerformed
      String prob =  probBox.getText();
       String ans = ansBox.getText();
        
       for( int i = 0; i< answers.length; i++){
       if(ans.equals(answers[i])){
         ansBox.setText("correct");
       }
       else{
          ansBox.setText("incorrect");
       }
        }
    }//GEN-LAST:event_ansButtonActionPerformed

    private void probButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probButtonActionPerformed
//        for(int i = (int)((Math.random()*10)); i< problems.length; i++){
for( int i = 0; i< answers.length; i++){
            probBox.setText(problems[i]);
        }
        
    }//GEN-LAST:event_probButtonActionPerformed

    private void heroHealthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heroHealthBoxActionPerformed
        String health = "500";
        health = Hero.getHealth;
        heroHealthBox.setText(health);
    }//GEN-LAST:event_heroHealthBoxActionPerformed

    private void enemyHealthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enemyHealthBoxActionPerformed
        String health = "500";
        health = Hero.getHealth;
        enemyHealthBox.setText(health);
    }//GEN-LAST:event_enemyHealthBoxActionPerformed

   
    public String[] problems = {
                "8*9",
                "9*20",
                "500-90",
                "10/2",
                "4^2",
                "2/3",
                "10^3" ,
                "4^3",
                "2*8",
                "6*0",
                "66/3",
                "22/11",
                "10/10",
                "67+33",
                "100/10",
                "1000-599",
                "89+11",
                "3^2 - 9",
                "5^2",
                "7^2",
                "9^2",
                "27/9",
                "72/9",
                "1000/100",
                "81/9",
                "99/9",
                "666/333",
                "777/111",
                "1^100",
                "0^999",
                "10^-1",
                "2^-1",
                "33^-3",
                "(33/3) / 11",
                "1000-560",
                "(100-31) / 3",
                "7*7",
                "8*12",
                "12*12",
                "13*1",
                "69/3",
                "42/0",
                "99/3",
                "1000^-3",
                "44 / (2^2)",
                "7*5",
                "3*2*10",
                "8*6",
                "12^2",
                "99^-3",
                "1^-1",
                "1/1",
                "0/0",
                "72/8",
                "32/8",
                "32/4",
                "32/2",
                "90/9",
                "999/999", 
            };
    
     public String[] answers = {
                "72",
                "180",
                "410",
                "5",
                "16",
                "0.666",
                "1000" ,
                "64",
                "16",
                "0",
                "22",
                "2",
                "1",
                "100",
                "10",
                "401",
                "100",
                "0",
                "25",
                "49",
                "81",
                "3",
                "8",
                "10",
                "9",
                "11",
                "2",
                "7",
                "1",
                "0",
                "1",
                "0.2",
                "0.33",
                "1",
                "440",
                "23",
                "49",
                "96",
                "144",
                "13",
                "23",
                "0",
                "33",
                "1",
                "11",
                "35",
                "60",
                "48",
                "144",
                "0.99",
                "0.1",
                "1",
                "0",
                "9",
                "4",
                "8",
                "16",
                "10",
                "1",  
            };
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextPane ansBox;
    private javax.swing.JButton ansButton;
    private javax.swing.JTextField enemyHealthBox;
    private javax.swing.JTextField heroHealthBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane probBox;
    private javax.swing.JButton probButton;
    // End of variables declaration//GEN-END:variables

//    void open() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
}
